config/routes.rb
Rails.application.routes.draw do
  # public内namespaseをルートとしてredirectするために配置
  root 'origins#top'

  devise_scope :user do
    post 'users/guest_sign_in', to: 'users/sessions#new_guest'
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :public do
    root 'reviews#index'
    get 'homes/about' => 'homes#about'
    get 'users/my_page/:id' => 'users#show', as: 'users/my_page'
    get 'search' => 'restaurants#search'
    resources :users, only: [:edit, :update]
    resources :reviews, only: [:show, :create, :edit, :update, :destroy]
    resources :restaurants, only: [:index, :show]
    resources :menus, only: [:index, :show] do
      resource :bookmarks, only: [:create, :destroy]
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>絶品グルメ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="http://maps.google.com/maps/api/js?key=<%= ENV['GOOGLE_API_KEY'] %>&language=ja"></script>
    <script src="https://kit.fontawesome.com/4e73ef2403.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="wrapper">
      <nav class="navbar navbar-static-top">
        <% if user_signed_in? %>
          <header>
            <div class="header-content">
              <%= link_to '', public_root_path, class: "logo" %>
              <div class="navbar-search">
                <%= form_tag(public_search_path, method: :get) do %>
                  <%= select_tag(:option, options_for_select([["レストラン", "1"],["メニュー","2"]]))%>
                  <%= text_field_tag :search, '', placeholder: "店名, メニュー名"%>
                  <button type="submit" class="btn-search"><i class="fas fa-search fa-fw"></i></button>
                <% end %>
              </div>
              <ul class="nav navbar-nav">
                <li><%= link_to 'お店を探す', public_restaurants_path %></li>
                <li><%= link_to 'マイページ', public_users_my_page_path(current_user.id) %></li>
                <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
                <span>
                <%= link_to public_users_my_page_path(current_user.id) do%>
                  <%= attachment_image_tag current_user, :profile_image, :fill, 200, 200, fallback: "no_image1.jpg", class:"img-circle header-profile", size:"45x45"%>
                <% end %>
                </span>
              </ul>
            </div>
          </header>
        <% else %>
          <header>
            <div class="header-content">
              <%= link_to '', public_root_path, class: "logo" %>
              <div class="navbar-search">
                <%= form_tag(public_search_path, method: :get) do %>
                  <%= select_tag(:option, options_for_select([["レストラン", "1"],["メニュー","2"]]))%>
                  <%= text_field_tag :search, '', placeholder: "店名, メニュー名"%>
                  <button type="submit" class="btn-search"><i class="fas fa-search fa-fw"></i></button>
                <% end %>
              </div>
              <ul class="nav navbar-nav">
                <li><%= link_to 'About', public_homes_about_path %></li>
                <li><%= link_to '新規登録', new_user_registration_path %></li>
                <li><%= link_to 'ログイン', new_user_session_path %></li>
              </ul>
            </div>
          </header>
        <% end %>
      </nav>

      <div class="container">
        <%= yield %>
      </div>

      <footer>Copyright © Zeppin Gourumet All Rights Reserved.</footer>
    </div>
  </body>
</html>